name: Echo Runner Machine Name

on:
  workflow_dispatch:

jobs:
  echo-machine-name:
    runs-on: [self-hosted, windows]
    environment:
      name: approval-required
    steps:
      - name: Echo PC Name
        run: |
          echo "Runner machine name: $env:COMPUTERNAME"
