name: Run DBATools Query

on:
  workflow_dispatch:
    inputs:
      sqlserverinstancename:
        description: 'SQL Server instance name (e.g., localhost, SERVER\INSTANCE)'
        required: true

jobs:
  run-dbatools-query:
    runs-on: [self-hosted, windows]
    steps:
      - name: Install DBATools
        shell: pwsh
        run: |
          Install-Module -Name dbatools -Force -Scope CurrentUser
          Set-DbatoolsConfig -FullName sql.connection.trustcert -Value $true -Register
          Set-DbatoolsConfig -FullName sql.connection.encrypt -Value $false -Register

      - name: Import DBATools and run query
        shell: pwsh
        run: |
          Import-Module dbatools
          Invoke-DbaQuery -SqlInstance ${{ github.event.inputs.sqlserverinstancename }} -Query 'select name from sysdatabases'

      - name: Get current disk space
        shell: pwsh
        run: |
          Get-DbaDiskSpace
