name: Run DBATools Query

on:
  workflow_dispatch:
    inputs:
      sqlserverinstancename:
        description: 'SQL Server instance name (e.g., localhost, SERVER\INSTANCE)'
        required: true

jobs:
  run-dbatools-query:
    runs-on: [self-hosted, windows]
    environment:
      name: approval-required


      - name: Import DBATools and run query
        shell: powershell
        run: |
          Import-Module dbatools
          try {
            Invoke-DbaQuery -SqlInstance ${{ github.event.inputs.sqlserverinstancename }} -Query 'select name from sysdatabases' -EnableException
          } catch {
            Write-Host 'Error: Something went wrong running Invoke-DbaQuery.'
            exit 1
          }

      - name: Restart all SQL Services on target machine
        shell: powershell
        run: |
          Import-Module dbatools
          $sqlInstance = '${{ github.event.inputs.sqlserverinstancename }}'
          if ($sqlInstance -like '*\\*') {
            $computerName = $sqlInstance.Split("\\")[0]
          } else {
            $computerName = $sqlInstance
          }
          try {
            Restart-DbaService -ComputerName $computerName -Type Engine,Agent -Force -EnableException
          } catch {
            Write-Host 'Error: Something went wrong restarting SQL Services.'
            exit 1
          }

      - name: Get current disk space
        shell: powershell
        run: |
          Import-Module dbatools
          $sqlInstance = '${{ github.event.inputs.sqlserverinstancename }}'
          if ($sqlInstance -like '*\\*') {
            $computerName = $sqlInstance.Split("\\")[0]
          } else {
            $computerName = $sqlInstance
          }
          try {
            Get-DbaDiskSpace -ComputerName $computerName -EnableException
          } catch {
            Write-Host 'Error: Something went wrong getting disk space.'
            exit 1
         