name: Run DBATools Query

on:
  workflow_dispatch:
    inputs:
      sqlserverinstancename:
        description: 'SQL Server instance name (e.g., localhost, SERVER\INSTANCE)'
        required: true

jobs:
  run-dbatools-query:
    runs-on: [self-hosted, windows]
    steps:
      - name: Import DBATools and run query
        shell: powershell
        run: |
          Import-Module dbatools
          Invoke-DbaQuery -SqlInstance ${{ github.event.inputs.sqlserverinstancename }} -Query 'select name from sysdatabases'

      - name: Restart all SQL Services on target machine
        shell: powershell
        run: |
          Import-Module dbatools
          $sqlInstance = '${{ github.event.inputs.sqlserverinstancename }}'
          if ($sqlInstance -like '*\\*') {
            $computerName = $sqlInstance.Split("\\")[0]
          } else {
            $computerName = $sqlInstance
          }
          Restart-DbaService -ComputerName $computerName -Type Engine,Agent -Force

      - name: Get current disk space
        shell: powershell
        run: |
          Import-Module dbatools
          $sqlInstance = '${{ github.event.inputs.sqlserverinstancename }}'
          if ($sqlInstance -like '*\\*') {
            $computerName = $sqlInstance.Split("\\")[0]
          } else {
            $computerName = $sqlInstance
          }
          Get-DbaDiskSpace -ComputerName $computerName
