name: Run DBATools Query

on:
  workflow_dispatch:
    inputs:
      sqlserverinstancename:
        description: 'SQL Server instance name (e.g., localhost, SERVER\INSTANCE)'
        required: true

jobs:
  show-variables:
    runs-on: [self-hosted, windows]
    steps:
      - name: Output all workflow variables
        shell: powershell
        run: |
          Write-Host "Workflow Inputs:"
          Write-Host "  sqlserverinstancename: ${{ github.event.inputs.sqlserverinstancename }}"
          Write-Host ""
          Write-Host "Environment Variables:"
          Get-ChildItem Env: | ForEach-Object { Write-Host "  $($_.Name)=$($_.Value)" }
          Write-Host ""
          Write-Host "GitHub Context:"
          Write-Host "${{ toJson(github) }}"

  run-dbatools-query:
    runs-on: [self-hosted, windows]
    needs: show-variables
    environment:
      name: approval-required
    steps:
      - name: Import DBATools and run query
        shell: powershell
        run: |
          Import-Module dbatools
          try {
            Invoke-DbaQuery -SqlInstance ${{ github.event.inputs.sqlserverinstancename }} -Query 'select name from sysdatabases' -EnableException
          } catch {
            Write-Host 'Error: Something went wrong running Invoke-DbaQuery.'
            exit 1
          }

      - name: Get current disk space
        shell: powershell
        run: |
          Import-Module dbatools
          $sqlInstance = '${{ github.event.inputs.sqlserverinstancename }}'
          if ($sqlInstance -like '*\\*') {
            $computerName = $sqlInstance.Split("\\")[0]
          } else {
            $computerName = $sqlInstance
          }
          try {
            Get-DbaDiskSpace -ComputerName $computerName -EnableException
          } catch {
            Write-Host 'Error: Something went wrong getting disk space.'
            exit 1
