name: Country Time

on:
  workflow_dispatch:
    inputs:
      country:
        description: 'Country name (e.g., Japan, Brazil, United Kingdom)'
        required: true
        default: 'Japan'

jobs:
  get-country-time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytz countryinfo
      - name: Get current time for country
        run: |
          python scripts/get_time.py "${{ github.event.inputs.country }}"